:toc:
:author: peicheng.liu@outlook.com

== 词汇

|===
|单词 |假名 |声调 |罗马音 |词义
|紅葉|もみじ|1|momiji|红叶
|故郷|こきょう|1|kokyou|故乡
|通り|とおり|3|toori|大街
|町|まち|2|machi|城市街道
|所|ところ|3|tokoro|场所
|お店|おみせ|0|omise|商店
|人形|にんぎょう|0|ningyou|玩偶
|作品|さくひん|0|sakuhin|作品
|彫刻|ちょうこく|0|choukoku|雕刻
|自動車|じどうしゃ|2|jidousha|汽车
|道具|どうぐ|3|dougu|工具
|魚|さかな|0|sakana|鱼
|お菓子|おかし|2|okashi|点心
|物|もの|2|mono|物品
|シーズン||1|shi-zun|季节
|修学旅行|しゅうがくりょこう|5|shougakuryokou|修学旅行
|観光客|かんこうきゃく|3|kankoukyaku|游客
|作家|さっか|0|sakka|作家
|部長|ぶちょう|0|buchou|部长
|平日|へいじつ|0|heijitsu|平日
|日|ひ||hi|日子
|生活|せいかつ|0|seikatsu|生活
|世界|せかい|1|sekai|世界
|晴れ|はれ|2|hare|晴天
|雨|あめ|1|ame|雨
|曇り|くもり|3|kumori|阴天
|雪|ゆき|2|yuki|雪
|汚い|きたない|3|katanai|脏
|綺麗|きれい|1|kirei|漂亮 干净
|有名|ゆうめい|0|yuumei|有名
|賑やか|にぎやか|2|nigiyaka|热闹
|静か|しずか|1|shizuka|安静
|暇|ひま|0|hima|空闲
|親切|しんせつ|1|shinsetsu|热情
|好き|すき|2|suki|喜欢
|嫌い|きらい|0|kirai|讨厌
|便利|べんり|1|benri|方便
|不便|ふべん|1|fuben|不方便
|元気|げんき|1|genki|健康
|簡単|かんたん|0|kantan|简单
|ハンサム||1|hunsamu|英俊 handsome
|どんな||1|donna|什么样的
|どう||1|dou|怎样
|いかが||2|ikaga|如何
|いろいろ||0|iroiro|各种各样
|でも||1|demo|可是
|そして||0|soshite|而且
|ところで||3|tokorode|转移话题
|あれえ||0|aree|咦
|奈良|なら|1|nara|奈良
|富士山|ふじさん|1|fujisan|富士山
|もう少し|もうすこし|4|mousukoshi|再~~一点
|～中|～じゅう|||
|===

== 语法


=== 名は 2类形容词です／でした

2类形容词做谓语时要在后面加です。

过去形式是でした。

[literal]
----
* 京都の　紅葉は　有名です。
* 　この　通りは　静かです。
* 　この　　町は　にぎやかでした。
* 昨日、王さんと一緒に紅葉を見ました。とてもきれいでした。
----

=== 名は2类形容词ではありません／ではありませんでした。

2类形容词做谓语时要在后面加ではありません。

过去形式是ではありませんでした。

[litearl]
----
* この　通りは　にぎやか　では　ありません。
* 　　　昨日は　暇　　　　じゃ　ありませんでした。
----

=== 名词は2类形容词な名です

2类形容词+な+名词。

[literal]
----
* 　　奈良は　　　静かな　町です。
* 　　奈良は　にぎやかな　町ではありません。
* トビ先生は　ハンサムな　先生です。
----

=== 名でした

名词做谓语时的过去形式是名词でした。

其否定形式是名词ではありませんでした。

[literal]
----
* 　　昨日は　日曜日　　　でした。
* おとといは　休み　　　　でした。
* 　　昨日は　雨では　　　ありませんでした。
* おとといは　曇りじゃ　　ありませんだした。
* 　　昨日は　土曜日では　ありませんでした。
----

=== どんな

どんな+名词，相当于汉语中的“什么样的”。

[literal]
----
A:横浜は　どんな　　　町ですか。
B:とても　にぎやかな　町です。

A:張さんは　どんな　人ですか。
B:親切な　　人です。
----

=== 何の　和　どんな

何の，有询问内容和材料两种用法。

[literal]
----
A:何の　　　本ですか。（内容）
B:自動車の　本です。

A:何の　料理ですか。（材料）
B:魚の　料理です。
----

どんな　询问性质。

[literal]
----
A:どんな　本ですか。（性质） 
B:面白い　本です。

A:どんな　　料理ですか。（性质）
B:ちょうと　辛い料理です。
----

=== どうですか

. どうですか

.. 询问对方对某状态的意见或感想时的表达方式。（现在或未来的事情）
.. 劝诱对方进行某动作。

. どうでしたか

.. 询问对方对某状态的意见或感想时的表达方式。（过去的事情）

[literal]
----
* この　料理は　どうですか。
* 京都は　どうでしたか。
* Ａ：お茶、どうですか。（相当于 どうぞ）
* Ｂ：ありがとう　ございます。
----

=== でも 和 そして

* でも，表示转折关系的连词。一般只用于口语，而不用与正式的书面语。正式表达/书面语应该用 しかし。
* そして，表示并列关系的连词。

[literal]
----
* わたしの　部屋は　狭いです。でも、きれいです。
* わたしの　部屋は　狭いです。そして、汚いです。
* この　　　料理は　とても　辛いです。でも、とても　美味しいです。
----

=== 常见的2类形容词

[literal]
----
好き　嫌い　にぎやか　静か

便利　不便　きれい　　暇

元気　簡単　親切　　　有名
----

=== 表达及词语讲解

. きれいです。
. おとといは　雨でした。
. あれえ
. ところで
. 世界中（全世界）
+
类似表达还有：日本中，学校中、一日中　いちにちちゅう、一晩中　いちばんちゅう、一年中　いちねんちゅう。
+
. 形容词+の
+
の相当于指示代词，省略前文的名词。比如，“面白いのがあります”。
+
. 紅葉，两种读法，もみじ 和 こうよう。
. 修学旅行。しゅうがく　りょこう。

== 课文

[literal]
----
A:どんな　お土産を　買いましたか。
B:きれいな　人形を　買いました。

A:京都は　どうでしたか。
B:とても　きれいでした。でも、静かでは　ありません。
　
A:横浜は　どうな　町ですか。
B:大きい　町です。そして　にぎやかな　町です。

A:京都の　天気は　どうでしたか。
B:昨日は　晴れでした。でも、おとといは　雨でした。
----

== 课后课文

[literal]
----
長島：昨日　京都ヘ　行きました。
小野：京都ですか。京都の　紅葉　どうでしたか。

長島：とても　きれいでした。でも、町は　あまり　静かじゃ　ありませんでした。
　李：えっ？

長島：今　ちょうど　修学旅行の　シーズンです。とても　にぎやかでした。
　李：この　通りは　静かですね。

長島：ああ、今日は　平日ですね。でも、休みの　日は　観光客が　多いです。とても　にぎやかですよ。
　李：そうですか。

　李：あれえ、だれも　いませんね。
小野：そうですね。

　李：ところで、この　美術館には　どんな　作品が　ありますか。
小野：世界中の　有名を　作家の　彫刻です。

長島：美術館の　庭にも　いろいろ　おもしろいのが　ありますよ。
----
