:toc:
:author: peicheng.liu@outlook.com

== 词汇

|===
|单词 |假名 |声调 |罗马音 |词义
|季節|きせつ|1|kisetsu|季节
|冬|ふゆ|2|fuyu|冬天
|春|はる|1|haru|春天
|夏|なつ|2|natsu|夏天
|秋|あき|1|aki|秋天
|日本料理|にほんりょうり|4|nihonryouri|日式饭菜
|寿司|すし|2|sushi|寿司
|ナシ||2|nashi|梨
|バナナ||1|banana|香蕉 banana
|ミカン||1|mikan|橘子
|焼酎|しょうちゅう|3|shouchuu|烧酒
|日本酒|にほんしゅ|0|nihonshu|日本酒
|紅茶|こうちゃ|0|koucha|红茶
|ウーロン茶||3|u-roncha|乌龙茶
|ジャスミン茶||3|jasumincha|茉莉花茶 jasmine
|緑茶|りょくちゃ|0|ryokucha|绿茶
|ジュース||1||果汁 juice
|人気||0|ninki|声望,受欢迎
|席|せき|1|seki|座位,席位
|クラス||1|kurasu|班级 class
|種類|しゅるい|1|shurui|种类
|背|せ（高い　たかい 低い　ひくい）|1|se|个子
|兄|ani（姉　あね）|1||哥哥,兄长
|最近|さいきん|0|saikin|最近,近来
|降ります|ふります|3|furimasu|下/降(雨/雪)
|若い|わかい|2|wakai|年轻
|暖かい|あたたかい|4|atatakai|暖和,温暖
|涼しい|すずしい|3|suzushii|凉爽
|速い|はやい|2|hayai|快
|大好き|大好き|1|daisuki|非常喜欢
|いちばん||0|ichiban|最,第一
|ずっと||0|zutto|~得多
|やはり／やっぱり||2-3|yahari/yappari|仍然,还是
|チョモランマ||3|chomoranma|珠穆朗玛峰
|人気があります|にんきがあります||ninkigaarimasu|受欢迎
|～年間|||~nenkan|
|===

== 语法

=== 名1は　名2より　1类形/2类形です

比较名词1和名词2，名词1比名词2更具有该句中形容词所表示的性质时使用 AはBよりOOでさ。

[literal]
----
* 李さんは　森さんより　若いです。
* 　中国は　　日本より　ひろいです。
* 　上海は　　北京より　にぎやかですか。
----

程度差异较大时用副词“ずっと”加以强调。

[literal]
----
* 　中国は　　　　日本より　ずっと　広いです。
* 王さんは　　佐藤さんより　ずっと　高いです。
----

=== 名1より　名2の　ほうが 1类形/2类形です

比较名词1和名词2，名词2比名词1更具有该句中形容词所表示的性质时使用 AよりBのほうがOOでさ。

[literal]
----
* 　　日本より　　　中国の　ほうが　広いです。
* 　　北京より　　　東京の　ほうが　暖かいです。
* 　　大坂より　　　東京の　ほうが　にぎやかですか。
* 佐藤さんより、　王さんの　ほうが　高いです。
----

=== 名1は　名2ほど　1类形く　ないです　/　2类形では　ありません

AはBほどOO(否定)です。

[literal]
----
* 　　東京の冬は　　　北京の冬ほど　寒く　ないです。
* 　　　　神戸は　　　　　大坂ほど　にぎやかでは　ありません。
* わたしの部屋は　王さんの部屋ほど　きれいでは　ありません。
* 　　佐藤さんは　　　　王さんほど　高くないです。
----

=== 名1の　中で　名2が 1类形/2类形です

在某个范围内，表示名词2最具有该句形容词的性质时使用这个句型。名词1为表示名词2所属范围的名词。

Aの中で、Bが一番ＯＯです。

[literal]
----
* スポーツの中で　サッカーが　いちばん　おもしろいです。
* 日本料理の中で　寿司が　いちばん　おいしいです。
----

如果名词1表示场所或者时间，则后面不加“の中”。而使用“名词1（场所/时间）で　いちばん [1/2类形] 名词2 は　名词3 です”.

[literal]
----
* 日本で　いちばん　高い　山は　富士山です。
* 一年で　いちばん　寒い　月は　二月です。
----

日语中的只能用于“～の中で”　“～で”等明确指出比较对象或者范围的情况。

=== 名1と　名2と　どちらが　1/2类形ですか

询问两种事物当中哪一种更具有该句形容词的性质时使用这个句型。

“どちら”是二选一时使用的疑问句。回答时使用“～の　ほうが～”。如果两者程度相当，则使用“どちらも～です”。

“どちら”在口语中有时说成“どっち”（dotchi）。

[literal]
----
* 日本語と　英語と　どちらが　難しいですか。
  日本語の　ほうが　難しいです。
* コーヒーと　紅茶と　どっちが　好きですか。
  紅茶の　ほうが　好きです。
  どちらも　好きです。
----

询问的范围为两种事物时，无论是人是物还是时间，都可以使用“どちらが”。但是询问范围为三种以上的事物是，则不能使用“でちら”。

=== どの　名／いつ　／どれ／だれ　／何が　いちばん　1/2类形ですか

询问三个以上事物中当中哪一个更具有后该句形容词的性质时，根据所询问对象的不同，须区别使用几种疑问词:是人则使用"だれが"，是物则使用"どの　～が" "どれが"或者"何が"，是时间则使用"いつが"。

[literal]
----
* この　中で　どの　料理が　いちばん　美味しいですか。
  この　料理が　いちばん　おいしいです。
* 季節の　中で　いつが　いちばん　好きですが。
  わたしは　春が　いちばん　好きです。
----

被选择的事物已经与上下文或存在眼前时,使用"どの～が"或"どれが",反之则用"何が".

[literal]
----
* リンゴと　ナシと　バナナの　中で　どれが　いちばん　好きですか。
* 果物の　中で　何が　いちばん　好きですか。
----

=== 表达及词语讲解

. 最近
+
中文的"最近"可以表示将来,日文的只表示过去到今天,或者过去.
+
. ～が　いいです
+
可以理解为"~~比较好",或者"我喜欢~~".
+
. やっぱり
+
正式说法是"やはり".
+
. ……が……[说半句话时]
+
例句:あのう、そこは　わたしの　席ですが。。。(这个,是我的位置吧...)
+
. お酒

== 课文

[litearl]
----
A:北京は　東京より　寒いです。
B:ええ、冬の　北京は　東京より　ずっと　寒いです。

A:日本語と　英語と　とちらが　難しいですか。
B:日本語の　ほうが　難しいです。

A:森さんは　テニスが　上手ですね。
B:いええ、長島さんほど　上手では　ありません。

A:季節の　中で　いつが　いちばん　好きですか。
B:わたしは　春が　いちばん　好きです。
----

== 课后课文

[litearl]
----
　李：長島さんは　よく　お酒を　飲みますか。
長島：ええ。お酒は　大好きですから、毎晩　飲みますよ。
　李：ビールと　日本酒と、どちらが　好きですか。
長島：どちらも　好きです。でも、焼酎が　いちばん　好きです。

小野：焼酎は　最近　人気が　ありますね。
　李：小野さんも　焼酎が　好きですか。
小野：いいえ。わたしは　焼酎より　ワインの　ほうが　いいです。でも、ビールも　よく　飲みますよ。

長島：中国は　お茶の　種類が　多いですね。
　李：ええ。ウーロン茶、ジャスミン茶、緑茶など、たくさん　あります。

小野：どの　お茶が　いちばん　人気が　ありますか。
　李：やっぱり　ウーロン茶です。
小野：李さんも　よく　飲みですか。

　李：ええ。毎日　ウーロン茶か　ジャスミン茶を　飲みます。
長島：どちらが　美味しいですか。
　李：どちらも　おいちですよ。わたしは　ジャスミン茶の　ほうが　好きですが……。
----
