:toc:
:author: peicheng.liu@outlook.com

== 词汇

|===
|单词 |假名 |声调 |罗马音 |词义
|荷物|にもつ|1|nimotsu|包裹
|はがき|はがき|0|hagaki|明信片
|切手|きって|0|kitte|邮票
|引き出し|ひきだし|0|hikidashi|抽屉
|アルバム|あるばむ|0|arubamu|相册 album
|タバコ|たばこ|0|tabako|烟，烟草 tabacco
|漫画|まんが|0|manga|漫画
|ガレージ||2|gare-ji|车库，汽车房 garage
|修理|しゅうり|1|shuuri|修理
|生ビール|なまビール|3|namabi-ru|生啤
|焼き鳥|やきとり|0|yakitori|烤鸡肉串
|唐揚げ|からあげ|0|karaage|炸鸡，油炸食品
|肉しゃが|にくしゃが|0|nikushaga|土豆炖肉
|ボーリング||0|bo-ringu|保龄球
|髪|かみ|2|kami|头发
|象|ぞう|1|zou|象，大象
|昼|ひる|2|hiru|白天，中午
|おか|おか|0|oka|另外，其他
|かかります||4|kakarimasu|【动1】花费（时间，金钱）
|咲きます|さきます|3|sakimasu|【动1】花开
|泳ぎます|およぎます|4|oyogimasu|【动1】游泳
|遊びます|あそびます|4|asobimasu|【动1】玩，玩耍
|吸います|すいます|3|suimasu|【动1】吸（烟）
|切ります|きります|3|kirimasu|【动1】剪，切，割
|大体|だいたい|0|daitai|大约，大概，大体
|とりあえず|とりあえず|3|toriaezu|暂且
||どのぐらい／どれぐらい|0|donogurai/doregurai|多久，多少钱
|===

== 语法

=== 名[数量] + 动

数量词用在动词前面。量词因所修饰的事物种类而不同。

[literal]
----
* 卵を   一個 食べました。一個 ikko
* 本を   二冊 買いました。二冊 nisatsu
* 緑茶を 三杯 飲みました。三杯 sanpai
* 教室に     学生が 四人 います。四人 yonin
* ガレージに   車が ５台 あります。５台 gotai
* 引き出しに 鉛筆が 十本 あります。十本 jupon
* 切手を 何枚 買いましたか。何枚 nanmai
----

=== 名【时间】に 名【次数】+ 动

表示在一定时间内进行若干次动作时，使用这个句型。

[literal]
----
* 李さんは　一週間に　二回　プールヘ　行きます。
* この　花は　二年に　一度　　　　　　咲きます。
* 王さんは　一週間に　五日　　　　　　働きます。
* 王さんは　毎日　　ゲームを　二時間　遊びます。
----

=== 动词的"ます"形

动词的“ます”去掉"ます"的形式会经常用到。

|===
|ます形|去掉ます
|働きます|はたらき
|休みます|やすみ
|起きます|おき
|寝ます|ね
|===

比如，动词＋たい，表示想要，如：働きたい、休みたい、起きたい、寝たい。

=== 名[场所]ヘ动に行きます/来ます

表示移动行为动目的时使用。动词用“ます形”去掉“ます”的形式，表示移动行为的目的。

[literal]
----
* 午後         郵便局ヘ 荷物を 出しに 行きます。
* 小野さんは    プールヘ       泳ぎに 行きます。
* 李さんは わたしの 家ヘ       遊びに 来ました。
* 王さんは      映画館ヘ  映画を 見に 行きます。
----

=== 名【數量」+で

用于不称重量而以数个的方式售物。数量是1个时，不加“で”。

[literal]
----
* この ケーキは 三個で 500円です。
* この ケーキは 一個   200円です。
----

=== 表达及词语讲解

. 数的用法
.. 数词和量词
.. 週に 二回
.. 生ビールを 3つ
. くらい/ぐらい
. どのぐらい かかりますか
+
例句：電車で 一時間 かかります。例句：修理に 【お金/時間】は いくら かかりますか。
+
. 飲みに行きます
+
默认表示“去喝酒”。【ジュース/コーラー】を飲みに行きます。表示去喝可乐/果汁。
+
. とりあえず


== 课文

[literal]
----
A:すみません、はがきを 五枚 ください。
B:はい。五枚で 250円です。

A:よく 映画を 見ますか。
B:ええ、一か月に 二回ぐらい見ます。

A:家から 会社まで どのぐらい かかりますか。
B:電車で一時間ぐらいかかります。

A:昨日 何を しましたか。 
B:新宿ヘ 映画を 見に 行きました。
----

== 课后课文

[literal]
----
小野：これから 森さんと 近くの お店ヘ 飲みに 行きます。李さんも 一緒に どうですか。
 李：えっ、いいですか。お願いします。
 李：森さんたちは この お店ヘ よく 来ますか。
 森：ええ、ぼくは 週に 二回ぐらい 来ます。
小野：わたしも よく 来ます。
 森：あのう、すみません。とりあえず 生ビールを 3つ お願いします。
 李：生ビールが 一杯 300円ですか。
 森：ここは お酒も 食べ物も 安いです。焼き鳥は 五本で 四百円ですからね。
小野：唐揚げや 肉じゃがは 一皿  三百五十円です。
 李：ほかの お店は いくらぐらいですか。
 森：生ビールは だいたい 一杯 四百円か 四百五十円ですね。
小野：焼き鳥は 一本 百五十円ぐらいですよ。
 李：じゃあ、ここは 安いですね。
----