:toc:
:author: peicheng.liu@outlook.com

== 单词

|===
|单词 |假名 |声调 |罗马音 |词义

|音|おと|2|oto|声音，响声
|声|こえ|1|koe|声音
|空気|くうき|1|kuuki|空气
|息子|むすこ|0|musuko|儿子
|医者|いしゃ|0|isha|医生
|お嬢さん|おじょうさん|2|ojousan|令爱
|社会人|しゃかいじん|2|shakaijin|社会的一员，成人
|旅行ガイド|りょこうガイド|4|ryokougaido|旅行导游
|学者|がくしゃ|0|gakusha|学者
|パイロット||1|pairotto|飞行员 pilot
|デザイナー||2|dezaina-|设计者，设计家 designer
|タイムサービス||4|taimusa-bisu|时段廉价销售 time service
|新春セール|しんしゅんセール|5|shinshunse-ru|新年大甩卖
|三割引|さんわりびき|3|sanwaribiki|七折
|定価|ていか|0|teika|定价
|半額|はんがく|0|hangaku|半价
|値段|ねだん|0|nedan|价格
|シャツ||1|shatsu|衬衫 shirt
|スカート||2|スカート|裙子 skirt
|色|いろ|2|iro|颜色
|赤|あか|1|aka|红色
|青|あお|1|ao|蓝色
|お正月|おしょうがつ|5|oshougatsu|过年，新年
|時間|じかん|0|jikan|时间
|将来|しょうらい|1|shourai|将来
|準備|じゅんび|1|junbi|准备
|病気|びょうき|0|byouki|疾病
|なります||3|narimasu|变，当，变成，成为
|開きます|あきます|3|akimasu|打开
|似合います|にあいます|4|niaimasu|适合，相称
|うるさい||3|urusai|吵，使人闹心
|シンプル||1|shinpuru|单纯，简洁 simple
|間もなく|まもなく|2|mamonaku|马上，一会儿，不久
|もうすぐ||3|mousugu|马上
|さらに||1|sarani|更加，更
|もっと||1|motto|更加，更
|さあ||1|saa|（叹）啊，喂
|できるだけ||0|dekirudake|尽量，尽可能
|まとめて||0|matomete|一下子，一起，汇总，汇集
|今から|いまから|1|imakara|从现在起
|===

|===
|单词|假名|单词|假名

|なります||まる|
|開きます|あきます|開く|あく
|似合います|にあいます|似合う|にあう
|===


== 语法

=== 一类形なります

|===
|一类形容词|~く なります

|暖かい|暖かく なります
|小さい|小さく なります
|安い|安く なります
|===

----
* だんだん 暖かく なります。
* 携帯電話は 小さく なりました。
* パソコンは 安く なりました。
* 空は 暗く なりました。
----

=== 一类形します

|===
|一类形容词|~く します

|大きい|大きく します
|冷たい|冷たく します
|===

----
* テレビの 音を 大きく します。
* ジュースを 冷たく します。
* 王さんは テレビの 音を 大きく しました。
----

=== 二类形/名に なります

表示性质或状态的变化。

|===
|二类形容词/名词|~に なります

|元気|元気に なります
|医者|医者に なります
|===

----
* もう 元気 に なりました。
* 息子は 医者に なりました。
* 来年 社会人 に なります。
----

=== 二类形/名 に します

表示因主语的意志性的动作、作用等而引起事物发生变化。

|===
|二类形容词/名词|~に します

|きれい|きれいに します
|禁煙|禁煙に します
|===

----
* 部屋 を きれい に して ください。
* 会議室 を 禁煙 に します。
----

在餐馆里回答服务员的点餐询问时，可以使用“~に します”这一形式，把自己决定的事情告诉对方的一种表达方式。

----
* カレーに します。
* コーヒーに します。
----

=== 一类形/二类形 ほうが いいです

比较两个以上事物的性质，认为其中一个比较好时，可用“一类形容词+ほうが いいです” “二类形容词+な+ほうが いいです”的形式，表示自己的选择或向别人提建议。

----
* 旅行の 荷物は 軽い  ほうが いいです。
*        部屋は 広い  ほうが いいです。
*        子供は 元気な ほうが いいです。
*        公園は 静かな ほうが いいです。
*     四川料理は 辛い  ほうが いいです。 
----

=== 自动词和他动词

日语的动词可分为自动词和他动词。

最典型的他动词具有主语作用于宾语而使其发生变化的含义，其宾语用“を”表示。

自动词是不带宾语的动词，表示不考虑外力影响的情况下，主语自主地进行动作，或自热地发生变化，其主语用“が”表示。

另外，日语的一部分自动词、他动词在词形上有对应关系。

----
*            窓 が 開きました。
* （李さんが）窓 を 開けました。
*             タイムサービス が 始まります。
* （デパートが）タイムサービス を 始めます。
----

~なります：自动词。

~します：他动词。

=== 表达及词语讲解

. “声”和“音”
+
--
人和动物的声音用“声 こえ”，物体的声音用“音 おと”。
----
* 子供の 声 が うるさいですね。
* テレビの 音 を  大きく します。
----
--

. まとめて
+
--
一下子。
----
* お正月は 洋服が 安く なりますから、まとめて 買います。
----
--

. 三割引
+
--
七折，30% off，的意思。“半額 はんがく”是打五折。
--

. 似合います
+
--
自动词，表示“合适”。
----
* 赤い ほうが いいですね。よく 似合いますよ。
* 小野さんは 浴衣が 似合います。
* この シャツは 父に 似合いません。派手ですよ。 
----
--
. “間もなく”和“もうすぐ”
+
--
都表示“一会儿/不久”，“間もなく”更正式，“もうすぐ”偏口语。
----
* 間もなく タイムサービスの 時間です。
* もうすぐ 六時に なります。
----
--

. “さらに”和“もっと”
+
都表示“更~”，“さらに”更正式，“もっと”偏口语。
--
----
* 間もなく タイムサービスの 時間です。さらに お安くします。
* 今から 七時まで もっと 安く なります。
----
--

. さあ
+
语气词。
--
----
* 今から 七時まで もっと 安く なります。さあ、行きましょう。
* さあ、今から 試験を 始めますよ。準備は いいですか。
----
--

. 新春セール
+
--
日本一般元旦前发年终奖，所以有新春促销。
--

== 课文

----
A: 風邪は どうですか。
B: ゆうべ 薬を 飲みましたが、まだ よく なりません。

A: 旅行の 荷物は 軽い ほうが いいですよ。
B: はい。できるだけ 軽く します。

A: お嬢さんは おいくつですか。
B: 今年 七歳に なりました。

A: あのう、ちょっと うるさいですよ。
B: あっ、すみません。静かに します。
----

== 课后文章

----
李: 小野さん、今日は たくさん 買いますか。
小野: ええ。お正月は 洋服が 安く なりますから、まとめて 買います。
李: どのぐらい 安く なりますか。
小野: だいたい 定価の 三割引か 半額に なります。
李: 半額ですか。わたしも 新しい 洋服が 欲しく なりました。
----

----
李: 赤と 青と どちらが いいですか。
小野: 赤い ほうが いいですね。よく 似合いますよ。
李: そうですか。じゃあ、これに します。
店員: 間もなく タイムサービスの 時間です。さらに お安く しますよ。
小野: もうすぐ 六時に なりますから、タイムサービスが 始まります。
李: タイムサービス？
小野: ええ、今から 七時まで もっと 安く なります。さあ、行きましょう。
----

== 作业 

. 外面的雨变大了。
+
外の雨が 大きく なりました。

. 儿子当医生了。
+
息子は 医者に なりました。

. 手机变小了。
+
携帯電話は 小さく なりました。