:toc:
:author: peicheng.liu@outlook.com

== 词汇

|===
|单词 |假名 |声调 |罗马音 |词义
|歌|うた|2|uta|歌曲
|カラオケ||0|karaoke|卡拉OK
|ロック||1|rokku|摇滚乐 rock
|ポップス||1|poppusu|流行音乐 pops
|クラシック||3|kurashikku|西方古典音乐 classic
|ピアノ||0|piano|钢琴 piano
|絵|え|1|e|画儿
|英語|えいご|0|eigo|英语
|スペイン語||0|supeingo|西班牙语
|スポーツ||2|supo-tsu|体育 sports
|水泳|すいえい|0|suiei|游泳
|ゴルフ||1|gorufu|高尔夫 golf
|運転|うんてん|0|unten|开车
|飲み物|のみもの|2|nomimono|饮料
|お酒|おさけ|0|osake|酒
|肉|にく|2|niku|肉
|野菜|やさい|0|yasai|蔬菜
|果物|くだもの|2|kudamono|水果
|ヒマワリ||2|himawari|向日葵
|バラ||0|bara|玫瑰
|コンピューター||3|kon-pyu-ta-|电脑 computer
|窓|まど|1|mado|窗户
|結婚式|けっこんしき|3|kekkonshiki|结婚典礼
|写真展|しゃしんてん|2|shashinten|摄影展
|旅館|りょかん|0|ryokan|旅馆
|別荘|べっそう|3|bessou|别墅
|寄木細工|よせぎざいく|4|yosegizaiku|木片儿拼花工艺品
|模様|もよう|0|moyou|花纹
|外国|がいこく|0|gaikoku|外国
|会議|かいぎ|1|kaigi|会议
|脚|あし　足|2|ashi|腿
|僕|ぼく|1|boku|我
|分かります|わかります||wakarimasu|明白
|迷います|まよいます||mayoimasu|犹豫
|できます|||dekimasu|会
|閉めます|しめます||shimemasu|关闭
|疲れます|つかれます||tsukaremasu|疲倦
|散歩します|さんぽします||sanposhimasu|散步
|怖い|こわい|2|kowai|害怕
|赤い|あかい|0|akai|红
|痛い|いたい|2|itai|疼痛
|上手|じょうず|3|jouzu|擅长
|下手|へた|2|heta|水平低
|苦手|にがて|0|nigate|不擅长
|時々|ときどき|0|tokidoki|有时
|よく||1|yoku|经常
|たまに||0|tamani|偶尔
|また||0|mata|再
|どうして||1|doushite|为什么
|だから||1|dakara|所以
|うーん|||u-n|嗯……
|けっこうです||1|kekkoudesu|不用
|きにいります||5|kiniirimasu|喜欢
|まど|||mado|等等
|===

== 语法

=== 名1は名2が

"好きです"、"嫌いです"、"怖いです"等表达情感的形容词可以以"[名1]は[名2]が 一类形容词、二类形容词です"的句型使用.

名词1表示情感主体,名词2表示情感对象.

[litereal]
----
* 小野さんは　　歌が　好きです。
* 　王さんは　　肉が　嫌いです。
* 　林さんは　　犬が　怖いです。
* 　王さんは　映画が　好きです。
----

=== 名1は名2が

"分かります"、"できます"、"上手です"、"下手です"、"" 等有关能力的词语也可以以"名1は 名2が 动词ます 一类动词 二类动词です"的句型使用.

[litereal]
----
* スミスさんは　　　　韓国語が　分かります。
* 　　わたしは　コンピュータが　できません。
* 　小野さんは　　　　　料理が　上手です。
* 　　わたしは　　　　ゲームが　下手です。
----

=== 名や名

助词"や"和"と"一样,也是用于连接名词.两者的区别在于"と"用于列举所有的项目,而"や"用于只列举许多项目中的两项,相当于汉语中的"~呀~什么的".并且"や"常常和"など"呼应使用,构成"～や～など".

[litereal]
----
* 吉田さんは　時々　中国や　韓国ヘ　行きます。
* 　森さんは　サッカーや　野球が　好きです。
* 　わたしは　お店で　野菜や　果物などを　買いました。
----

=== "から～"和"だから"[原因/理由]

说明原因理由时用助词"から"."から"位于陈述原因理由的小句句尾.通常是在说明原因理由之后再陈述结论,但有时也可以先陈述结论再说明原因理由,不过无论哪一种情况,"から"都须接在表示原因理由小句的句尾.构成复句的句子我们称之为小句.

[literal]
----
* 森さんは　お酒が　好きですから、毎日　飲みます。
* 寒いですから、窓を　閉めます。
* 窓を　閉めます。寒いですから。 
* 暑い（です）から、窓を　開けました。
----

"だから"是表示原因理由的连词,意思相当于汉语的"所有",其实比较礼貌的说法是"ですから".助词"から"构成表示原因理由小句的一部分,而连词"だから"独立使用在结果的句子前面.

[literal]
----
* キムさんは　野菜が　嫌いです。だから、あまり　野菜を　食べません。
* 明日は　休みです。ですから、子供と　動物園ヘ　行きます。
* 明後日は試験がありますから。今晩、徹夜します。
----

～から

* [一类形容词,动词]+から
+
暑いから、食べますから
+
* [二类形容词,名词]+でから／ですから
+
好きでから、好きですから、学校でから、学校ですから
+

=== 表示频率的副词

"いつも" "よく" "時々" "たまに" "あまり" "全然"等是表示频率的副词."あまり"　"全然"后面须接否定形式.

[literal]
----
* 　わたしは　たまに　コンサートヘ　行きます。
* 　李さんは　時々　映画を　見ます。
* 田中さんは　あまり　横浜ヘは　行きません。
* 　わたしは　あまり　アニメを　見ません。
----

=== どうしてですか

询问事由时使用"どうしてですか",相当于汉语中的"为什么".回答说在谓语后面加"から".

[litereal]
----
A:ぼくは　来月　また　ここヘ　きますよ。
B:どうしてですか。
A:ここで　友達の　結婚式が　ありますから。
----

=== 表达及词语讲解

. ぼく
+
僕　ぼく、わたし、俺　おれ。
+
. ホテルで　写真展が　あります
+
存在句子,这里不用に,而用で,因为是一个持续的活动,同样用法的类似的词还有　パーティー、展覧会、会議、結婚式。
+
. いかがですか
+
你觉得如何啊?(对长辈和陌生人使用),熟人用どうですか。例如:日本の食べ物は　どうですか。そうですね、とても　おいしいです。でも　ちょうと　たかい。
+
. そうですね
. 迷います
+
うーん、迷いますね。(嗯,好难决定啊.)道に迷います。(迷路)
+
. 気に入りました。
+
仅用于第一次见到某物而感到中意,其对象用が表示.仅用于朋友熟人间,不能对长辈使用.而"好きです"一般用于持续性的爱好.
+
. 省略[避免重复谓语的回答方式]
+
在回答对方提问时,人们尽量不重复对方的话,采用省略的方式回答.例句:北京ダックは　おいしいですね。ええ、とても（おいしいです）。
+

== 课文

[literal]
----
A:吉田さんは　料理が　できますか。
B:いいえ、全然　できません。

A:どうな　音楽が　好きですか。
B:ロックや　ポップスなどが　好きです。

A:長島さん、スペイン語語が　分かりますか。
B:ええ、大学で　習いましたから、少し　分かります。

A:小野さん、よく　音楽を　聞きますか。
B:ええ、家で　ＣＤを　よく　聞きます。そして、たまに　コンサートヘ　行きます。
----

== 课后课文

[literal]
----
　李：箱根は　ホテルや　旅館が　多いですね。
小野：そうですね。会社の　別荘も　たくさん　あります。
　李：長島さんや　小野さんも　よく　来ますか。
長島：ええ、車で　時々　来ます。

小野：わたしは　うんてんが　できませんから、いつも　電車です。
長島：ぼくは　来月　また　きますよ。
　李：どうしてですか。
長島：この　近くの　ホテルで　友達の　写真展が　ありますから。

　李：箱根の　お土産は　何が　いいですか。
小野：うーん、そうですね……、迷いますね。
長島：寄木細工は　いかがですか。とでも　有名ですよ。

　李：きれいな模様ですね。
小野：ええ。
長島：気に入りましたか。
　李：はい、とても。
----
