:toc:
:author: peicheng.liu@outlook.com

== 单词

|===
|单词 |假名 |声调 |罗马音 |词义

|品物|しなもの|0|shinamono|物品，商品
|お皿|おさら|0|osara|盘子
|ごみ||2|gomi|垃圾
|初心者|しょしんしゃ|2|shoshinsha|初学者
|上級者|じょうきゅうしゃ|2|joukyuusha|熟练者
|高級|こうきゅう|0|koukyuu|高级
|上級クラス|じょうきゅうクラス|5|joukyuukurasu|高级班
|英会話|えいかいわ|3|eikaiwa|英语会话
|コース||1|ko-su|路线，滑道 course
|スキー||2|suki-|滑雪 ski
|レポート||2|repo-to|报告 report
|パスポート||3|pasupo-to|护照 passport
|のど||1|nodo|喉咙
|触ります|さわります|4|sawarimasu|碰，触
|脱ぎます|ぬぎます|3|nugimasu|脱
|転びます|ころびます|4|korobimasu|摔，摔倒，跌倒
|渇きます|かわきます|4|kawakimasu|渴
|治ります|なおります|4|naorimasu|痊愈，医好
|滑ります|すべります|4|suberimasu|滑，滑行
|呼びます|よびます|3|yobimasu|呼喊
|返します|かえします|4|kaeshimasu|归还
|手伝います|てつだいます|5|tetsudaimasu|帮忙
|運びます|はこびます|4|hakobimasu|搬运
|なくします||4|nakushimasu|丢，丢失
|落とします|おとします|4|otoshimasu|掉，使落下
|置きます|おきます|3|okimasu|放置
|払います|はらいます|4|haraimasu|支付
|立ちます|たちます|3|tachimasu|站，立
|忘れます|わすれます|4|wasuremasu|忘记
|慌てます|あわてます|4|awatemasu|慌张，惊慌，着急
|捨てます|すてます|3|sutemasu|仍，扔掉
|残業します|ざんぎょうします|6|zangyoushimasu|加班
|心配します|しんぱいします|shinpaishimasu||担心
|本当|ほんとう|0|hontou|真的，真正
|早く|はやく|1|hayaku|早点儿
|やっと||0|yatto|好不容易，终于
|だいぶ||0|daibu|很，相当地
|初めて|はじめて|2|hajimete|第一次
|先に|さきに|0|sakini|先
|山田|やまだ|0|yamada|山田
|===

|===
|单词|假名|单词|假名

|触ります|さわります|触る|さわる
|脱ぎます|ぬぎます|脱ぐ|ぬぐ
|転びます|ころびます|転ぶ|ころぶ
|渇きます|かわきます|渇く|かわく
|治ります|なおります|治る|なおる    
|滑ります|すべります|滑る|すべる
|呼びます|よびます|呼ぶ|よぶ
|返します|かえします|返す|かえす
|手伝います|てつだいます|手伝う|てつだう
|運びます|はこびます|運ぶ|はこぶ
|なくします|なくす||
|落とします|おとします|落とす|おとす
|置きます|おきます|置く|おく
|払います|はらいます|払う|はらう
|立ちます|たちます|立つ|たつ
|忘れます|わすれます|忘れる|わすれる
|慌てます|あわてます|慌てる|あわてる
|捨てます|すてます|捨てる|すてる
|残業します|ざんぎょうします|残業する|ざんぎょうする
|心配します|しんぱいします|心配する|しんぱいする
|===


== 语法

== ない形

|===
|类别 |原形 |ます形 |ない形 |规律

.9+|一类动词
|書く かく |かきます |かかない
.9+|う段 -> あ段，特例是 う -> わ
|急ぐ いそぐ |いそぎます |いそがない
|飛ぶ とぶ |とびます |とばない
|読む よむ |よみます |よまない
|死ぬ しぬ |しにます |しなない
|待つ まつ |まちます |またない
|売る うる |うります |うらない
|買う かう |かいます |かわない
|話す はなす |はなします |はなさない

.2+|二类动词
|食べる 食べる |食べます |たべない
.2+|去掉る
|見る みる |みます |みない

.2+|三类动词
|来る くる |きます |にない |来る -> き
|する |します |しない |する -> し、せ、さ
|===

=== 动 ないで ください

表示否定的命令时，使用“~て ください”的否定形式。其构成方式为“未然形 + ないで + ください”。

----
* 部屋の かぎを 忘れ ないで ください。
* この 部屋には 入ら ないで ください。 
*        無理を  し ないで ください。
* 部屋で  食事を  し ないで ください。
* 部屋の中で、ご飯を 食べ ないで ください。
----

=== 动 なければ なりません

表示必须。接续方法是将动词“ない形”中的“ない”换成“なければ ないません”。也可以用“ないと いけません”的形式代替“なければ なりません”。

----
* 李さんは 今日 早く 帰ら なければ なりません。
* この 薬は 毎日 飲ま なければ なりません。
* すぐに 書類を 送ら ないと いけません。
* 私は 宿題を かか なければ なりません
----

=== 动 なくても いいです

表示不做某事也可以。意思相当于“~なければ なりません”的否定。接续方法是将动词“ない”换成“なくても いいです”。

----
* 明日は 残業し なくても いいです。
*         慌て なくても いいですよ。 
* 靴を ぬが なくても いいですか。
* 明日、運動し なくても いいです。
----


=== 名1が 名2です

表示作为话题的“名词2”是什么时，用“【名词2】は【名词1】です”的形式。这里“名词2”是旧信息，“名词1”是新信息。

同样的内容也可以用“【名词1】が【名词2】です”来表示。在这个句型里“名词1”仍然是新信息，“名词2”仍然是旧信息。新信息做主语时用“が”来表示。

----
* 山田先生は どの 方ですか。
-- 山田先生は あの 方です。
-- あの 方が 山田先生です。
* 吉田課長は いますか。
-- わたしが 吉田ですが……。
-- 吉田は 私です。
* あなたの かばんは どれですか。
-- これが わたしの かばんです。
-- わたしの かばんは これです。
----

叙述直接观察到的某事物，而不是作为话题在谈论这个事物时，使用“【名词】が【名词】”的形式。因为这里也同样是新信息在做主语。

----
* 母：バスは まだ来ませんか。
--娘：あっ、バスが 来ました。
* 子供が 公園で  遊んで います。
* バスが 来ました。
----

“何”、“だれ”、“どこ”、“いつ”等表示疑问的词作主语时不能用“は”，只能用“が”。因为这些词不能表示旧信息。

----
* だれが いますか。
* どこが 痛いですか。
* なにが 好きですか。
----

=== 表达及词语讲解

. “なければ なりません”和“ないと いけません”
+
--
前者更正式，后者更随意。

----
* 子供は 六歳から 学校ヘ 行かなければ なりません。
* あっ、八時ですね。もう 駅ヘ 行かないと。
----
--

. “初心者”和“上級者”
+
--
----
* 森さん、英会話の 勉強は どうですか。
--やっと 先月 上級クラスに 入りました。
----
--

. 何度も
+
--
表示多次。
----
* 何度も 転びましたが、とても おもしろいです。
* のどが 渇きましたから、水を 何杯を 飲みました。
----
--

. だいぶ（表示程度的副词）
+
--
----
* 昨日は だいぶ お酒を 飲みました。
* 風邪は よく なりましたか。
--だいぶ よく なりました。
----
--

. 大丈夫です
+
--
表示“没问题”，“我可以的”，“我保证”。
----
* 上級者の コースには 入らないで ください。
--大丈夫です。心配しないで ください。
* 田中さん、病気は もう 治りましたか。
--はい、もう 大丈夫です。
----
--

== 课文

----
A：その 品物に 触らないで ください。
B：あっ、すみません。

A：李さん、いっしょに 食事に 行きませんか。
B：すみません。今日は 早く 帰って レポートを 書かなければ なりません。

A：先生、もう 薬を 飲まなくても いいですか。
B：はい、いいですよ。

A：吉田課長は いますか。
B：わたしが 吉田ですが……。
----

== 课后文章

スキー

----
 李：小野さん、初めてですから、ちょっと 怖いです。
小野：心配しなくても いいですよ。ここは 初心者コースですから。
 李：森さん、小野さん、待って ください。先に 行かないで ください。
小野：急がなくても いいですよ。私達も ゆっくり 滑りますから。
 森：李さん、スキーは どうですか。
 李：何度も 転びましたが、とても 面白いです。
 森：そうですか。だいぶ 上手に なりましたよ。
 李：本当ですか。でも、もっと 上手に なりたいです。
小野：じゃあ、もっと 練習しなければ なりませんね。もう 一度 滑りますか。
 李：はい。今度は 先に 滑っても いいですか。
小野：いいですよ。でも、上級者の コースには 入らないで ください。
 李：大丈夫です。心配しないで ください。
----

== 作业

. 请别忘了房间的钥匙。
+
部屋の かぎを 忘れ ないで ください。
+
. 小李今天必须早点回家。
+
李さんは 今日 早く 帰ら なければ なりません。
+
. 王老师，我可以不写作业吗。--当然不可以。
+
王さん、私は 宿題を 書かなくても いいですか。--もちろ いけませんよ。
+