:toc:
:author: peicheng.liu@outlook.com

== 单词

|===
|单词 |假名 |声调 |罗马音 |词义

|洋服|ようふく|0|youfuku|西服
|セーター||1|se-ta-|毛衣
|ノートパソコン||4|no-topasokon|笔记本电脑
|バイク||1|baiku|摩托车 bike
|お汁粉|おしるこ|2|oshiruko|年糕小豆汤
|天ぷら|てんぷら|0|tenpura|天妇罗
|初詣|はつもうで|3|hatsumoude|新年后首次参拜
|健康|けんこう|0|kenkou|健康
|恋愛|れんあい|0|renai|恋爱
|ドラマ||1|dorama|连续剧
|相手|あいて|3|aite|对象，对方
|恋人|こいびと|0|koibito|恋人
|先輩|せんぱい|0|senpai|前辈
|男性|だんせい|0|dansei|男性
|女性|じょせい|0|josei|女性
|外国人|がいこくじん|4|gaikokujin|外国人
|夏|なつ|2|natsu|夏天
|今年|ことし|0|kotoshi|今年
|始めます|はじめます|4|hajimemasu|开始
|連絡します|れんらくします|6|renrakushimasu|联系
|欲しい|ほしい|2|hoshii|想要
|立派|りっぱ|0|rippa|美观，杰出
|今度|こんど|1|kondo|下次；这回
|ぜひ||1|zehi|一定
|そろそろ||1|sorosoro|快要 
|まず||1|mazu|先，首先
|ベートーベン||3|be-to-ben|贝多芬
|ショパン||1|shopan|肖邦
|故宮|こきゅう|1|kokyuu|故宫
|ヨーロッパ||3|yo-roppa|欧洲
|香港|ホンコン|1|honkon|香港
|スイス||1|suisu|瑞士
|~中に|~じゅうに||~juuni|
|===

|===
|单词|假名|单词|假名

|始めます|はじめます|始める|はじめる
|連絡します|れんらくします|連絡する|れんらくする
|===


== 语法


=== 名が 欲しいです

表示愿望时使用“【名词1】は【名词2】が 欲しいです”这一句式。“名词1”是愿望的主体，“名词2”是表示愿望的对象。

----
* わたしは 新しい 洋服が 欲しいです。
* （あなたは）何が 欲しいですか。
  -- 新しい パソコンが 欲しいです。
* わたしは 新しい パソコンが 欲しいです。
----

=== 名を 动たいです

动词ます去掉ます，然后

. 加上たい，表示想要。
. 加上たく ない，表示不想要。

----
* （わたしは） 映画 を 見たいです。
* 今日は お酒 を 飲みたく ないです。
* （あなたは） 何 を したいですか。
  -- 何 も したく ありません。
* 私は 公園ヘ 行きたいです。
----

“たい”的对象有时不用“を”，而用“が”表示。但“欲しい”的对象只能用“が”来表示。

比如，“水 **を** 飲みたいです”可以换成“水 **が** 飲みたいです”。

比如，“学校 **に** 行きたいです”**不**可以换成“学校 **が** 行きたいです”。

比如，“水 **が** 欲しいです”不可以换成“水 **を** 欲しいです”。

名词+に/から/と+动词 => にも/からも/とも+动词否定，比如：

----
* たれに 会いたいですか。
  -- だれにも 会いたくないです。
----

名词+ヘ+动词 => ヘも/も + 动词否定，比如：

----
* どこヘ 行きたいですか。
  -- どこヘも 行きたくないです。
  -- どこも   行きたくないです。
----

=== 动ませんか

动词的否定形式“~ません”加上表示疑问的“か”，表面上是一种疑问形式，但其语法功能是表示提议。


----
* いっしょに お茶を 飲みませんか。
* 少し 休みませんか。
* 明日 故宮ヘ 行きませんか。
* 家で 休みませんか。
----

=== 动 ましょう

把动词“ます形”的“ます”换成“ましょう”可表示提议。不如上面的“ませんか”礼貌。

----
* ちょうと 休みましょう。
* そろそろ 行きましょう。
* いっしょに お茶を 飲みましょう。
* いっしょに テレビを 見ましょう。
----

=== 疑问词 でも

表示在任何情况下事态都相同是，使用“疑问词+でも”。

----
* 李さん、何を 食べたいですか。
  -- 何でも いいです。
* いつでも 電話を して ください。
* だれでも 分かります。
* この 問題は 誰でも 書けます。
----

=== ね（缓和语气）

----
* 日本料理で 何が いちばん 好きですか。
  -- そうですね。やっぱり お寿司 ですね。
----


=== 表达及词语讲解

. 欲しいです / 飲みませんか
+
--
何が 欲しいですか。这个只能对平辈、晚辈使用。对长辈，可以用下面的说法：

----
* デパートヘ 買い物に 行きます。李さんも いっしょに *どうですか*。
  -- はい、行きたいです。
* コンサートヘ 行き**ませんか**。
  -- いいですね。行きましょう。
----
--

. 中に
+
--
今日 / 明日 / 今年 + 中，读作「じゅう」。

~週 / 月 + 中，读作「ちゅう」。

----
* 今年中に 結婚したいです。
* この 仕事は 今日中に 終わります。
* 来週中に もう 一度 連絡します。
----
--

. ぜひ
+
--
----
* お汁粉？ぜひ 食べたいです。
* 今度 ぜひ 家ヘ 遊びに 来て ください。
----
--

. お汁粉

. 初詣

== 课文

----
A: 今 何が いちばん 欲しいですよ。
B: 安い 車が 欲しいです。

A: 今日 でポートヘ 買い物に 行きます。李さんも いっしょに どうですか。
B: はい ぜひ 行きたいです。

A: 李さん、何を 食べたいですよ。
B: 何でも いいです。

A: 土曜日の午後、コンサートヘ 行きませんか。
B: いいですね。行きましょう。
----

== 课后文章

----
李：小野さんは 何を お願いしましたか。
小野：健康と 恋愛です。
李：恋愛ですか。
小野：ええ。今年中に 結婚したいです。
李：相手は いますか。
小野：いいえ。まず 恋人が 欲しいですね。
李：どうな 男性が いいですか。
小野：まじめで 優しい 人が いいですね。
李：じゃあ、森さんは どうですか。
小野：ええ？
----

----
小野：ちょうと 寒いですね。温かい 物を食べませんか。
李：そうですね。
小野：何が いいですか。
李：何でも いいですよ。
小野：じゃあ、お汁粉は どうですか。いい お店を 知って います。そこに 行きましょう。
李：お汁粉？ぜひ 食べたいです。
----


== 作业

. 我想吃母亲的菜。
+
私は母の料理を食べたいです。
+
. 想去哪里？--哪里都行。
+
どこに行きたいますか。--どうでもいいです。
+
. 周六下午去听音乐会好吗？--好啊，去吧！
+
土曜日の午後、コンサートヘ行きませんか。--いいですね。行きましょう。
+