:toc:
:author: peicheng.liu@outlook.com

== 单词

|===
|单词 |假名 |声调 |罗马音 |词义

|趣味|しゅみ|1|shumi|爱好
|特技|とくぎ|1|tokugi|特长，拿手的技术
|興味|きょうみ|1|kyoumi|兴趣
|夢|ゆめ|2|yume|梦；理想
|ギター||1|gita-|吉他
|胡弓|こきゅう|1|kokyuu|胡琴
|書道|しょどう|1|shodou|书法
|釣り|つり|0|tsuri|钓鱼
|ドライブ||2|doraibu|兜风，开汽车远游
|編み物|あみもの|2|amimono|编制；编织品
|手作り|てづくり|2|tezukuri|手工做，自己做，手制
|中華街|ちゅうかがい|3|chuukagai|中华街
|中華料理|ちゅうかりょうり|4|chuukaryouri|中国菜
|餃子|ギョーザ|0|gyo-za|饺子
|皮|かわ|0|kawa|皮
|春節|しゅんせつ|0|shunsetsu|春节
|獅子舞|ししまい|0|shishimai|狮子舞
|寮|りょう|1|ryou|宿舍
|洗濯機|せんたくき|4|sentakuki|洗衣机
|シャワー||1|shawa-|淋浴 shower
|おなか||0|onaka|肚子
|授業|じゅぎょう|1|jugyou|授课，上课
|資料|しりょう|1|shiryou|资料
|フランス語|フランスご|0|furansugo|法语
|小説|しょうせつ|0|shousetsu|小说
|海岸|かいがん|0|kaigan|海岸
|冬休み|ふゆやすみ|3|fuyuyasumi|寒假
|キャンプ||1|kyanpu|野营 camp
|みんな||3|minna|大家
|自分|じぶん|0|jibun|自己
|全員|ぜんいん|0|zenin|全员
|弾きます|ひきます|3|hikimasu|弹
|すきます||3|sukimasu|（肚子）饿，空
|登ります|のぼります|4|noborimasu|登，上
|集めます|あつめます|4|atsumemasu|收集
|浴びます|あびます|3|abimasu|淋；浇
|ごちそうします||6|gochisoushimasu|请客，摆盛宴
|帰国します|きこくします|5|kikokushimasu|回国
|特に|とくに|1|tokuni|特别
|おなかがすきます||7|onakagasukimasu|肚子饿
|===


|===
|单词|假名|单词|假名

|弾きます|ひきます|弾く|ひく
|すきます||すく|
|登ります|のぼります|登る|のぼる
|集めます|あつめます|集める|あつめる
|浴びます|あびます|あびる|あびる
|ごちそうします||ごちそうする|
|帰国します|きこくします|帰国する|きこくする
|===

== 语法

=== 动词的“ます形”和“基本型”

“基本型”是动词的基本形式。词典中的词条都使用这一形式，因此也叫辞书形。各类动词“ます形”去掉“ます”的形式和“基本型”的对应关系如下：

. 一类动词：“ます形”去掉“ます”词尾“い”段变成“う”段。
. 二类动词：“ます形”去掉“ます”后加“る”。
. 三类动词：“します”变“する”、“来ます”变“来る”。

|===
|类别|ます形|去掉ます|基本型

.9+|一类动词
|書きます |かき |書く かく
|急ぎます |いそぎ |急ぐ いそぐ
|飛びます |とび |飛ぶ とぶ
|読みます |よみ |読む よむ
|死にます |しに |死ぬ しぬ
|待ちます |まち |待つ まつ
|売ります |うり |売る うる
|買います |かい |買う かう
|話します |はなし |話す はなす

.2+|二类动词
|食べます |たべ |食べる たべる
|見ます |み |見る みる

.2+|三类动词
|来ます |き |来る きる
|します |し |する
|===

=== 名【人】は 动词（基本型）ことが できます

“动词基本型+ことができます”表示能力。

----
* スミスさんは ピアノを 弾く ことが できます。
* 森さんは 中華料理を 作る ことが できますか。
--はい、できます。
* 王さんは 小説を 書くことが できます。
----

=== 名は 动（基本形） ことです

当谓语部分的内容是一种动作、行为时使用这个句型。

----
* わたしの 趣味は 切手を 集める ことです。
* 王さんの 特技は 胡弓を 弾く   ことです。
* 森さんの 夢は   外国で 働く   ことです。
* わたしの 夢は   先生に なる   ことです。
----

“动词基本型+こと”可以起到和名词同样的作用。（类似英语中的动名词。）

----
* 小野さんは 車を 運転する こと が できません。
* 小野さんは 車の 運転         が できません。
----
=== 动（基本型）前に、~

表示一个动作在另一个动作之前发生时，使用这个句型。

----
* こちらヘ 来る 前に 電話を かけて ください。
* 毎日 寝る 前に シャワーを 浴びます。
* 会社を 出る 前に、私に 言って ください。
----

这个句型也可以以“名词+の+前に”的形式使用。

----
* 会議 の 前に、資料を コピーします。
----

=== 疑问词+か

疑问词“いつ”、“どこ”、“だれ”等词后续“か”，表示“某时”、“某地”、“某人”等意思。

----
* 部屋に だれか いますか。（房间里有人吗？）
* 部屋に だれが いますか。（房间里是谁啊？）
----

“いつか”、“どこか”、“だれか”、“何か”等本身并不表示疑问的意思，所以可用于陈述句。

----
* 冬休み、どこかヘ 行きたいです。
* おなかが すきましたね。何か 食べましょう。
----

=== ~よね

表示提出自己的意见，以征求对方的认可。

当说话人确信对方和自己的意见、想法完全相同时，只用“ね”，说话人对自己的意见、想法没有足够的把握时用“よね”。

----
* 手作りの 餃子の 皮は おいしですよね。
* この 傘は 森さんの ですよね。
* 小野さんも いっしょに 行きますよね。
----

=== 表达及词语讲解

. 写真を 撮る ことが できます【可能和允许】
+
--
----
* 日本では 何歳から 結婚する ことが できますか。
--女の 人は 十六歳から、男の 人は 十八歳から ですます。
* 寮の 洗濯機は 何時まで 使う どこが できますか。
--八時までです。それからは 使う ことが できません。
----
--

. みんなで
+
--
みんなで、自分で、全員で。
----
* みんなで 餃子を 作ります。
* 先月 クラス 全員で キャンプヘ 行きました。
----
--

. “趣味”和“興味”
+
--
前者爱好，后者是感兴趣。
----
* わたしの 趣味は 切手を 集める ことです。
* わたしは 日本の 書道に 興味が あります。
----
--

. ごちそうします
+
--
请别人吃饭的意思。
----
* わたしは 時々 家で 李さんに 日本料理を ごちそうします。
* あの 先生は 授業が 終わってから、よく 学生に ごちそうします。
----
--

== 课文

----
A：李さんは 車を 運転する ことが できますか。
B：はい、できます。

A：ここで 写真を 撮っても いいですか。
B：いいえ、ここでは 撮る ことが できません。

A：何か 趣味が ありますか。
B：ええ。音楽を 聞く ことです。

A：森さんは いつ ギターを 練習しますか。
B：毎晩、寝る 前に 練習します。
----

== 课后文章

春節

----
小野：李さん、春節は 中国ヘ 帰りますか。
 李：いいえ、今 日本の 仕事が 忙しいですから、帰りません。
 森：じゃあ、いっしょに 何処かヘ 行きませんか。
小野：横浜の 中華街ヘ 行きましょうよ。中国の 獅子舞を 見ることができますよ。
小野：料理は どうでしたか。
 李：とても おいしかったですよ。特に 餃子は。
 森：李さんは 餃子を 作る ことができますか。
 李：ええ。北京では 春節の 前に、家族みんなで 餃子を 作ります。
小野：手作りの 餃子は 皮が おいしいですよね。
 李：小野さんも 作る ことが できますか。
小野：ええ、もちろん。わたしの 趣味は おいしい物を 作る ことですから。
 森：本当ですか？じゃあ、いつか ごちそうしてください。
小野：いいですよ。李さんが 帰国する 前に、ぜひ いっしょに うちに 来て ください。
----

== 作业

. 小王会弹钢琴。
+
王さんは ピアノを 弾く ことが できます。
+
. 你有什么爱好吗？--有啊，打篮球。
+
何か趣味がありますか。--もちろん、バスケットボールです。
+
. 来这儿之前请打个电话。
+
こちらヘ 来る 前に 電話を かけて ください。
+