:toc:
:author: peicheng.liu@outlook.com

== 词汇

|===
|单词 |假名 |声调 |罗马音 |词义

|来月|らいげつ|1|raigetsu|下个月
|先月|せんげつ|1|sengetsu|上个月
|夜中|よなか|3|yonaka|午夜，半夜
|昨夜|ゆうべ|0|yuube|昨天晚上
|コンサート|こんサーと|1|konsa-to|音乐节 concert
|クリスマス|くりすます|3|kurisumasu|圣诞节
|誕生日|たんじょうび|3|tanjoubi|生日
|こどもの日|こどものひ|5|kodomonohi|儿童节
|夏休み|なつやすみ|3|natsuyasumi|暑假
|交通機関|こうつうきかん|5|koutsuukikan|交通工具
|新幹線|しんかんせん|3|shinkansen|新干线
|飛行機|ひこうき|2|hikouki|飞机
|フぇリー|ふぇリー|1|fuxeri-|渡轮
|電車|でんしゃ|0|densha|电车
|バス|ばす|1|basu|公共汽车
|タクシー|たくしー|1|takushi-|出租车
|美術館|びじゅつかん|3|bijutsukan|美术馆
|アパート|あぱーと|2|apa-to|公寓
|うち|うち|0|uchi|家
|プール|ぷーる|1|pu-ru|游泳池
|友達|ともだち|0|tomodachi|朋友
|弟|おとうと|4|otouto|弟弟
|行きます|いきます|3|ikimasu|去
|帰ります|かえります|4|kaerimasu|回来
|来ます|きます|2|kimasu|来
|たしか|たしか|1|tashika|好像是，大概
|まっすぐ|まっすぐ|3|massugu|笔直
|一緒に|いっしょに|0|isshoni|一起
|佐藤|さとう|1|satou|佐藤
|北京|ペキン|1|pekin|北京
|アメリカ|あめりか|0|amerika|美国
|韓国|かんこく|1|kankoku|韩国
|フランス|ふらんす|0|furansu|法国
|広島|ひろしま|0|hiroshima|广岛
|京都|きょうと|1|kyouto|京都
|北海道|ほっかいどう|3|hokkaidou|北海道
|箱根|はこね|0|hakone|箱根
|銀座|ぎんざ|0|ginza|银座
|渋谷|しぶや|0|shibuya|涩谷
|新宿|しんじゅく|0|shinjuku|新宿
||おつかれさまでした|7||够累的
||おさきにしつれいします|10||我先走了，我先告辞了
|歩いて|あるいて|2|aruite|步行
|大変ですね|たいへんですね|5|taihendesune|真不容易

|===

|===
|一月|いちがつ
|二月|にがつ
|三月|さんがつ
|四月|しがつ
|五月|ごがつ
|六月|ろくがつ
|七月|しちがつ
|八月|はちがつ
|九月|くがつ
|十月|じゅうがつ
|十一月|じゅういちがつ
|十二月|じゅうにがつ
|何月|なんがつ
|一日|ついたち
|二日|ふつか
|三日|みっか
|四日|よっか
|五日|いつか
|六日|むいか
|七日|なのか
|八日|ようか
|九日|ここのか
|十日|とおか
|十一日|じゅういちにち
|十四日|じゅうよっか
|二十日|はつか
|二十四日|にじゅうよっか
|何日|なんにち
|===

== 语法

=== 名词【场所】ヘ动词

使用 行きます　帰ります　等表示移动的动词时，移动行为的目的地用助词ヘ（读作え）表示。

[literal]
----
* 吉田さんは　中国ヘ　行きます。
* 　森さんは　日本ヘ　帰ります。
* 　李さんは　どこヘ　行きましたか。
* 　昨日、　　どこヘ　行きましたか。
----

=== 名词【场所】から动词

使用移动动词时，移动的起点用助词から表示。

[literal]
----
* 李さんは　先月　北京から　来ました。
* あの方は　　　　どこから　来ましたか。
* わたしは　　　　中国から　来ました。
----

=== 名词【人】と动词

共同做某事的对象用助词と表示。

[literal]
----
* 　　　小野さんは　友達と　　帰りました。
* 　　　李さんは　　だれと　　日本ヘ　来ましたか。
* 毎日、わたしは　　王さんと　一緒に　学校ヘ　行きます。
----

=== 名词【交通工具】で动词

交通手段用助词で表示。不适用交通工具而步行时用　歩いて。

[literal]
----
* 上海まで　　飛行機で　　　　　　　　行きます。
* 私は　　　　　バスで　　家ヘ　　　　帰ります。
* 李さんは　　　歩いて　　アパートー　帰りました。
* 京都ヘ　　　　　何で　　　　　　　　来きましたか。　
* 王さんは　タクシーで　　家ヘ　　　　帰ります。
----

=== 名词【场所】から　名词【场所】まで　动词

表示移动的范围时，范围的起点用から、终点用まで。

[literal]
----
* 李さんは　駅から　　　　アパートまで　　　歩いて　　帰りました。
* 森さんは　東京から　　　　　広島まで　　新幹線で　　行きます。　
* 李さんは　アメリカから　　　北京まで　　飛行機で　　行きます。
* 李さんは　飛行機で　　アメリカから　　　北京まで　　行きます。
----

=== 表达和词语讲解

. たしか（好像是）
+
あの人は　誰ですか。たしか、王さんです。（那人谁啊？好像是小王。）
+
. です　使用（2）（省略）
+
何で　帰りましたか。[.line-through]##電車で　帰りました。##電車です。（你怎么回来的？搭电车。）
+
. いえ　うち
いえ更偏向建物（たてもの），うち更多表示家族（かぞく）。うち本身就是“我家”，わたしのいえ才是“我的家”。
. まっすぐ帰りました
+
反义词是“道草（みちくさ）”，翻译是“路上耽擱、繞道”。
+
. それ （那个、那件事）
+
それは　お疲れ様でした。
+
. お疲れ様でした
. 終電（末班车）
+
最終電車　さいしゅう　　でんしゃ
+


=== 课文

[literal]
----
A:いつ　　アメリカヘ　行きますか。
B:十月に　行きます。

A:駅ヘ　何（なに）で　行きますか。
B:自転車で　行きます。

A:だれと　美術館ヘ　行きますか。
B:友達と　行きます。

A:大阪から　上海まで　飛行機で　行きますか。
B:いいえ、フぇリーで　行きます。
----

=== 课后课文

[literal]
----
吉田：李さん、昨日は　何時に　アパートヘ　帰りましたか。
李　：ええと、たしか　十一時半ごろです。

吉田：何で　帰りましたか。タクシーですか。
李　：電車です。渋谷まで　電車で　行きました。駅から　アパートまで　歩いて　帰りました。

吉田：小野さんは？
小野：私も　電車です。駅からは　タクシーで　うちヘ　帰りました。

李　：何時に　帰りましたか。
小野：十二時ごろです。

小野：森さん、昨夜は　まっすぐ　帰りましたか。
森　：いいえ、課長と　一緒に　銀座ヘ　行きました。

李　：えっ、銀座ですか？
小野：何時に　うちヘ　帰りましたか。

森　：夜中の　二時です。
李　：二時ですか。それは　お疲れ様でした。
----

